<div class="page-head">
    <h3><?php echo $this->__('You\'re All Set') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>


<fieldset class="group-select">
    <legend><?php echo $this->__('What TODO next?') ?></legend>
    <h4 class="legend"><?php echo $this->__('Checklist: Next possible actions') ?></h4>
    <ul>
        <li>
            <input type="checkbox">
            <label>Mage-Setup ausführen</label>
        </li>
        <li>
            <input type="checkbox">
            <label  >Logo und Favicon ändern/einspielen</label>
        </li>
        <li>
            <input type="checkbox">
            <label>Content, Content, Content</label>
        </li>
        <li>
            <input type="checkbox">
            <label>Konfiguration mit dem Kunden durchgehen</label>
        </li>
    </ul>
</fieldset>

<p><?php echo $this->__('Get ready to experience Open-Source eCommerce Evolved.') ?></p>
<?php if($this->getEncryptionKey()): ?>
    <p><?php echo $this->__('Before you continue to your store, please make a note of your encryption key (Magento uses it to encrypt passwords, credit cards and more).') ?></p>
    <p><strong><big><?php echo $this->getEncryptionKey() ?></big></strong></p>
    <p><?php echo $this->__('(Make sure you keep it in a safe place.)') ?></p>
<?php endif; ?>
<div class="button-set">
    <button class="form-button" onclick="window.open('<?php echo $this->getUrl('') ?>')" type="button"><?php echo $this->__('Go to Frontend') ?></button>&nbsp;&nbsp;
    <button class="form-button" onclick="window.open('<?php echo $this->getUrl('adminhtml') ?>')" type="button"><?php echo $this->__('Go to Backend') ?></button>
</div>
